- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - wget # for downloading freepbx
    - git # for using the git module
    - libmyodbc # for asterisk cdr
    - sudo # required by freepbx install script
    - net-tools # fwconsole requirement
    - cron # required by freepbx ucp package
    - gnupg1 # debian stretch provides gpg2 by default
  when: item != 'libmyodbc' or
        ansible_distribution != 'Debian' or
        ansible_distribution_version | version_compare('9' '<')

- name: Install asterisk
  apt: name=asterisk state=present
  when: freepbx_install_asterisk

- name: Download freepbx
  command: wget -O freepbx.tgz http://mirror.freepbx.org/modules/packages/freepbx/freepbx-13.0-latest.tgz
  args:
    chdir: /usr/src
    creates: /usr/src/freepbx

- name: Unpack freepbx
  command: "{{ item }} chdir=/usr/src creates=freepbx"
  with_items:
    - tar vxfz freepbx.tgz
    - rm freepbx.tgz

- name: Add asterisk user
  user: name=asterisk

- name: Install required pear package (but not from pear ;))
  command: composer require pear/console_getopt
  args:
    chdir: /usr/src/freepbx/amp_conf/htdocs/admin/libraries/Composer
    creates: vendor/pear/console_getopt

- name: Get freepbx devtools
  git:
    repo: http://git.freepbx.org/scm/freepbx/devtools.git
    dest: /usr/src/freepbx-devtools
    depth: 1
    update: no

# After installing freepbx, the framework module only consists of the directory
# `/var/www/freepbx/admin/modules/framework` with very few files, so signing
# this is useless and we must sign the src before installing.
# (This appears to be the same as freepbx does it, as the path's are `amp_conf/`
# in the original module.sig too)
# However, in the src tarball there are some additional files that would
# be getting signed but not installed, so we need to patch the signing tool
# to exclude these files.
# (Signing is necessary due to the changed composer files by installing
# `pear/console_getopt`)
- name: Patch devtools sign.php
  patch: src=sign.patch dest=/usr/src/freepbx-devtools/sign.php

- name: Create a signing key
  shell: >
    echo "Key-Type: 1\\nKey-Length: 2048\\nName-Real: Local Freepbx signing key\\nExpire-Date: 0" | gpg --batch --gen-key
  args:
    creates: /home/asterisk/local_signing_key.pub
  register: freepbx_signing_key_status

- name: Get signing key
  shell: "gpg --with-colons --list-keys 'Local Freepbx signing key' | awk -F: '/^pub:/ { print $5 }'"
  changed_when: false
  register: freepbx_signing_key

- name: Export signing key
  shell: gpg --export -a {{ freepbx_signing_key.stdout }} > /home/asterisk/local_signing_key.pub
  args:
    creates: /home/asterisk/local_signing_key.pub

- name: Import signing key for asterisk user
  command: su - asterisk -c 'gpg --import /home/asterisk/local_signing_key.pub'
  when: freepbx_signing_key_status|changed

# we can get the key using `gpg --with-colons --list-keys "Local Freepbx signing key" | awk -F: '/^pub:/ { print $5 }'`
- name: Sign framework
  command: /usr/src/freepbx-devtools/sign.php . --local {{ freepbx_signing_key.stdout }} --framework
  args:
    chdir: /usr/src/freepbx
    creates: /var/www/freepbx

- name: Install python-mysqldb (required for ansible mysql_* modules)
  apt: pkg=python-mysqldb state=present

- name: Add mysql user
  mysql_user:
    name: "{{ asterisk_db_user }}"
    password: "{{ asterisk_db_password }}"
    priv: "{{ asterisk_db_dbname }}.*:ALL/{{ asterisk_db_cdrdbname }}.*:ALL"
    login_host: "{{ asterisk_db_host }}"
    host: "{{ (asterisk_db_host == 'localhost') | ternary('localhost', ansible_default_ipv4.address) }}"
    state: present

- name: Add mysql db
  mysql_db:
    name: "{{ asterisk_db_dbname }}"
    encoding: utf8
    collation: utf8_general_ci
    login_host: "{{ asterisk_db_host }}"
    state: present

- name: Add cdr mysql db
  mysql_db:
    name: "{{ asterisk_db_cdrdbname }}"
    encoding: utf8
    collation: utf8_general_ci
    login_host: "{{ asterisk_db_host }}"
    state: present

- name: Setup logrotate
  copy:
    src: logrotate
    dest: /etc/logrotate.d/asterisk
    mode: 0644
    owner: root
    group: root

- name: Set permissions
  file: path={{ item }} state=directory owner=asterisk group=asterisk recurse=yes
  with_items:
    - /var/run/asterisk
    - /etc/asterisk
    - /var/lib/asterisk
    - /var/log/asterisk
    - /var/spool/asterisk
    - /usr/lib/asterisk
  register: freepbx_set_permissions
  changed_when: (ansible_env.CI is not defined or not ansible_env.CI) and freepbx_set_permissions|changed

- name: Disable Asterisk service and stop asterisk
  service: name=asterisk enabled=no state=stopped
  changed_when: false # this apparantly always reports changed

# using named groups due to this: http://www.handverdrahtet.org/2016/01/ansible-using-numbered-backreference.html
- name: Enable freepbx installation with remote mysql db
  replace:
    dest: /usr/src/freepbx/installlib/installcommand.class.php
    regexp: '(?P<firstpart>\$amp_conf\[.AMPDBHOST.\] = .)localhost(.;)'
    replace: '\g<firstpart>{{ asterisk_db_host }}\2'

- name: Fix freepbx install script to use remote CDR db
  lineinfile:
    dest: /usr/src/freepbx/installlib/installcommand.class.php
    line: >-
      $installer_amp_conf['CDRDBHOST'] = '{{ asterisk_db_host }}';
    insertafter: "{{ '$installer_amp_conf = $amp_conf;'|regex_escape() }}"

- name: Fix freepbx install script to use cdr db (only works if cdrdbtype is specified...)
  lineinfile:
    dest: /usr/src/freepbx/installlib/installcommand.class.php
    line: >-
      $installer_amp_conf['CDRDBTYPE'] = 'mysql';
    insertafter: "$installer_amp_conf.*CDRDBHOST'"

- name: Install freepbx (just ran once)
  command: "{{ item }}"
  args:
   chdir: /usr/src/freepbx
   creates: /var/www/freepbx
  with_items:
    - ./start_asterisk start
    - ./install -n --webroot /var/www/freepbx --dbuser {{ asterisk_db_user }} --dbpass {{ asterisk_db_password }} --dbname {{ asterisk_db_dbname }} --cdrdbname {{ asterisk_db_cdrdbname }}
  register: freepbx_installation

# http://community.freepbx.org/t/freepbx-12-check-online-fails-on-raspi/24270/52
- name: Re-install ucp so assets are generated
  command: fwconsole ma downloadinstall ucp
  when: freepbx_installation|changed

- name: Don't let freepbx take over the php sessions dir
  blockinfile:
    content: |
      [blacklist]
      directory = /var/lib/php5/sessions
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
    dest: /etc/asterisk/freepbx_chown.conf
    owner: asterisk
    group: asterisk
    create: yes

- name: Install systemd freepbx service
  copy: src=freepbx.service dest=/etc/systemd/system/freepbx.service mode=755
  when: ansible_service_mgr == "systemd"

- name: Install upstart freepbx service
  copy: src=freepbx.upstart dest=/etc/init/freepbx.conf
  when: ansible_service_mgr == "upstart"

- name: Find libmyodbc.so
  shell: dpkg -L libmyodbc |grep libmyodbc.so$
  changed_when: false
  register: freepbx_libmyodbc_result

# http://community.freepbx.org/t/fixing-cdr-cel-on-ubuntu-debian-installation/30836
# Test using `isql -v MySQL-asteriskcdrdb`
- name: Fix asterisk cdr odbc connection (1)
  blockinfile:
    dest: /etc/odbcinst.ini
    create: yes
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
    content: |
      [MySQL]
      Description = ODBC for MySQL
      Driver      = {{ freepbx_libmyodbc_result.stdout }}
      FileUsage   = 1
  notify: Reload asterisk modules

- name: Fix asterisk cdr odbc connection (2)
  replace:
    dest: /etc/odbc.ini
    regexp: /var/lib/mysql/mysql.sock
    replace: /var/run/mysqld/mysqld.sock
  notify: Reload asterisk modules

- name: Install freepbx modules
  command: "fwconsole ma downloadinstall {{ item }}"
  args:
    creates: /var/www/freepbx/admin/modules/{{ item }}
  with_items: "{{ freepbx_modules }}"

- name: Enable freepbx service
  service: name=freepbx enabled=yes
  when: ansible_connection != 'docker'

- name: Start freepbx
  service: name=freepbx state=started
  when: ansible_connection != 'docker'
  register: freepbx_started

